blank_issues_enabled: false

contact_links:
  - name: engine  proposals
    url: https://github.com/OmioRahman/omidot/
    about: Please submit feature proposals on the   proposals repository, not here.

  - name: engine documentation repository
    url: https://github.com/OmioRahman/omidot/
    about: Please report issues with documentation on the   documentation repository, not here.

  - name:   community channels
    url: https://github.com/OmioRahman/omidot/
    about: Please ask for technical support on one of the other community channels, not here.
