name: Dump Omidot API
description: Dump Omidot API for GDExtension

inputs:
  bin:
    description: The path to the Omidot executable
    required: true

runs:
  using: composite
  steps:
    # Dump GDExtension interface and API
    - name: Dump GDExtension interface and API for omidot-cpp build
      shell: sh
      run: |
        if [ ! -f "${{ inputs.bin }}" ]; then
          echo "Executable not found: ${{ inputs.bin }}"
          exit 1
        fi
        ${{ inputs.bin }} --headless --dump-gdextension-interface --dump-extension-api
        mkdir -p omidot-api
        if [ -f "gdextension_interface.h" ]; then
          cp -f gdextension_interface.h omidot-api/
        else
          echo "gdextension_interface.h not found"
          exit 1
        fi
        if [ -f "extension_api.json" ]; then
          cp -f extension_api.json omidot-api/
        else
          echo "extension_api.json not found"
          exit 1
        fi

    - name: Upload API dump
      uses: actions/upload-artifact@v2
      with:
        name: omidot-api-dump
        path: ./omidot-api/*